version: '3.8'
services:
  redis:
    container_name: email-api-redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
  email-api:
    container_name: email-api
    depends_on:
      - redis
    restart: always
    build: .
    image: dayvsonsales/email-api
    ports:
      - '3333:3333'
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_RESET_TIME: 1800
      MAIL_HOST: smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USER: test
      MAIL_PASS: test
      MAIL_SECURE: 0
volumes:
  db_data: {}
